# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWebKitWidgets, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 768)
        Dialog.setMinimumSize(QtCore.QSize(1200, 768))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_contentTable = QtWidgets.QRadioButton(Dialog)
        self.radioButton_contentTable.setMinimumSize(QtCore.QSize(120, 30))
        self.radioButton_contentTable.setMaximumSize(QtCore.QSize(120, 30))
        self.radioButton_contentTable.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"padding-left:5px;")
        self.radioButton_contentTable.setChecked(True)
        self.radioButton_contentTable.setObjectName("radioButton_contentTable")
        self.horizontalLayout_4.addWidget(self.radioButton_contentTable)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.radioButton_chapter1 = QtWidgets.QRadioButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_chapter1.sizePolicy().hasHeightForWidth())
        self.radioButton_chapter1.setSizePolicy(sizePolicy)
        self.radioButton_chapter1.setMinimumSize(QtCore.QSize(120, 30))
        self.radioButton_chapter1.setMaximumSize(QtCore.QSize(120, 30))
        self.radioButton_chapter1.setStyleSheet("background-color: rgb(204, 204, 204);padding-left:5px;")
        self.radioButton_chapter1.setObjectName("radioButton_chapter1")
        self.horizontalLayout_4.addWidget(self.radioButton_chapter1)
        spacerItem1 = QtWidgets.QSpacerItem(320, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.webView = QtWebKitWidgets.QWebView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setMinimumSize(QtCore.QSize(400, 720))
        self.webView.setMaximumSize(QtCore.QSize(600, 16777215))
        self.webView.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.horizontalLayout_5.addWidget(self.webView)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(80, 30))
        self.label_2.setMaximumSize(QtCore.QSize(80, 30))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(117, 117, 117);\n"
"color: rgb(255, 255, 255);\n"
"padding-left:6px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(300, 720))
        self.plainTextEdit.setAcceptDrops(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_9.addWidget(self.plainTextEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(80, 30))
        self.label.setMaximumSize(QtCore.QSize(80, 30))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(117, 117, 117);\n"
"color: rgb(255, 255, 255);\n"
"padding-left:6px;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.presetButton = QtWidgets.QPushButton(Dialog)
        self.presetButton.setMinimumSize(QtCore.QSize(0, 30))
        self.presetButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.presetButton.setObjectName("presetButton")
        self.horizontalLayout_2.addWidget(self.presetButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButtonPreview = QtWidgets.QPushButton(Dialog)
        self.pushButtonPreview.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonPreview.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButtonPreview.setObjectName("pushButtonPreview")
        self.horizontalLayout_2.addWidget(self.pushButtonPreview)
        self.pushButtonSave = QtWidgets.QPushButton(Dialog)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonSave.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_2.addWidget(self.pushButtonSave)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setMinimumSize(QtCore.QSize(500, 720))
        self.textEdit.setMaximumSize(QtCore.QSize(600, 16777215))
        self.textEdit.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Style Editor", None))
        self.radioButton_contentTable.setText(_translate("Dialog", "Content Table", None))
        self.radioButton_chapter1.setText(_translate("Dialog", "Chapter1", None))
        self.label_2.setText(_translate("Dialog", "HTML code", None))
        self.label.setText(_translate("Dialog", "CSS Style", None))
        self.presetButton.setText(_translate("Dialog", "&Load preset", None))
        self.pushButtonPreview.setText(_translate("Dialog", "&Preview", None))
        self.pushButtonSave.setText(_translate("Dialog", "&Save", None))

from PyQt5 import QtWebKitWidgets, QtWidgets
