# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(650, 420)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 420))
        MainWindow.setMaximumSize(QtCore.QSize(650, 420))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet(_fromUtf8("background-color:#f8f8f8;"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(650, 420))
        self.centralwidget.setMaximumSize(QtCore.QSize(650, 420))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.novelLayout = QtGui.QHBoxLayout()
        self.novelLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.novelLayout.setMargin(0)
        self.novelLayout.setSpacing(0)
        self.novelLayout.setObjectName(_fromUtf8("novelLayout"))
        self.novelLabel = QtGui.QLabel(self.centralwidget)
        self.novelLabel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.novelLabel.sizePolicy().hasHeightForWidth())
        self.novelLabel.setSizePolicy(sizePolicy)
        self.novelLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.novelLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.novelLabel.setFont(font)
        self.novelLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.novelLabel.setStyleSheet(_fromUtf8("padding-left:5px;background-color:#CCCCCC;color:#000000;"))
        self.novelLabel.setObjectName(_fromUtf8("novelLabel"))
        self.novelLayout.addWidget(self.novelLabel)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.novelLayout.addItem(spacerItem)
        self.novelSelector = QtGui.QComboBox(self.centralwidget)
        self.novelSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.novelSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.novelSelector.setFont(font)
        self.novelSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.novelSelector.setStyleSheet(_fromUtf8("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
""))
        self.novelSelector.setFrame(True)
        self.novelSelector.setObjectName(_fromUtf8("novelSelector"))
        self.novelLayout.addWidget(self.novelSelector)
        self.verticalLayout_2.addLayout(self.novelLayout)
        self.modeLayout = QtGui.QHBoxLayout()
        self.modeLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.modeLayout.setContentsMargins(0, -1, -1, -1)
        self.modeLayout.setSpacing(0)
        self.modeLayout.setObjectName(_fromUtf8("modeLayout"))
        self.modeLabel_1 = QtGui.QLabel(self.centralwidget)
        self.modeLabel_1.setMinimumSize(QtCore.QSize(250, 25))
        self.modeLabel_1.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.modeLabel_1.setFont(font)
        self.modeLabel_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeLabel_1.setStyleSheet(_fromUtf8("padding-left:5px;background-color:#CCCCCC;color:#000000;"))
        self.modeLabel_1.setObjectName(_fromUtf8("modeLabel_1"))
        self.modeLayout.addWidget(self.modeLabel_1)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem1)
        self.modeLabel_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeLabel_2.sizePolicy().hasHeightForWidth())
        self.modeLabel_2.setSizePolicy(sizePolicy)
        self.modeLabel_2.setMinimumSize(QtCore.QSize(60, 25))
        self.modeLabel_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.modeLabel_2.setFont(font)
        self.modeLabel_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeLabel_2.setStyleSheet(_fromUtf8("background-color:#FFFFFF;"))
        self.modeLabel_2.setFrameShape(QtGui.QFrame.Box)
        self.modeLabel_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.modeLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.modeLabel_2.setObjectName(_fromUtf8("modeLabel_2"))
        self.modeLayout.addWidget(self.modeLabel_2)
        spacerItem2 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem2)
        self.modeSlider = QtGui.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.modeSlider.setFont(font)
        self.modeSlider.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeSlider.setMinimum(0)
        self.modeSlider.setMaximum(1)
        self.modeSlider.setProperty("value", 0)
        self.modeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.modeSlider.setObjectName(_fromUtf8("modeSlider"))
        self.modeLayout.addWidget(self.modeSlider)
        spacerItem3 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem3)
        self.modeLabel_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeLabel_3.sizePolicy().hasHeightForWidth())
        self.modeLabel_3.setSizePolicy(sizePolicy)
        self.modeLabel_3.setMinimumSize(QtCore.QSize(60, 25))
        self.modeLabel_3.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.modeLabel_3.setFont(font)
        self.modeLabel_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeLabel_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.modeLabel_3.setStyleSheet(_fromUtf8("background-color:#FFFFFF;"))
        self.modeLabel_3.setFrameShape(QtGui.QFrame.Box)
        self.modeLabel_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.modeLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.modeLabel_3.setObjectName(_fromUtf8("modeLabel_3"))
        self.modeLayout.addWidget(self.modeLabel_3)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.modeLayout)
        self.totalExportLayout = QtGui.QHBoxLayout()
        self.totalExportLayout.setContentsMargins(0, -1, -1, -1)
        self.totalExportLayout.setSpacing(0)
        self.totalExportLayout.setObjectName(_fromUtf8("totalExportLayout"))
        self.totalExportLabel_1 = QtGui.QLabel(self.centralwidget)
        self.totalExportLabel_1.setMinimumSize(QtCore.QSize(250, 25))
        self.totalExportLabel_1.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.totalExportLabel_1.setFont(font)
        self.totalExportLabel_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportLabel_1.setStyleSheet(_fromUtf8("padding-left:5px;background-color:#CCCCCC;color:#000000;"))
        self.totalExportLabel_1.setObjectName(_fromUtf8("totalExportLabel_1"))
        self.totalExportLayout.addWidget(self.totalExportLabel_1)
        spacerItem5 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem5)
        self.totalExportLabel_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalExportLabel_2.sizePolicy().hasHeightForWidth())
        self.totalExportLabel_2.setSizePolicy(sizePolicy)
        self.totalExportLabel_2.setMinimumSize(QtCore.QSize(60, 25))
        self.totalExportLabel_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.totalExportLabel_2.setFont(font)
        self.totalExportLabel_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportLabel_2.setStyleSheet(_fromUtf8("background-color:#FFFFFF;"))
        self.totalExportLabel_2.setFrameShape(QtGui.QFrame.Box)
        self.totalExportLabel_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.totalExportLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.totalExportLabel_2.setObjectName(_fromUtf8("totalExportLabel_2"))
        self.totalExportLayout.addWidget(self.totalExportLabel_2)
        spacerItem6 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem6)
        self.totalExportSlider = QtGui.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.totalExportSlider.setFont(font)
        self.totalExportSlider.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportSlider.setMaximum(1)
        self.totalExportSlider.setProperty("value", 0)
        self.totalExportSlider.setOrientation(QtCore.Qt.Horizontal)
        self.totalExportSlider.setInvertedAppearance(True)
        self.totalExportSlider.setObjectName(_fromUtf8("totalExportSlider"))
        self.totalExportLayout.addWidget(self.totalExportSlider)
        spacerItem7 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem7)
        self.totalExportLabel_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalExportLabel_3.sizePolicy().hasHeightForWidth())
        self.totalExportLabel_3.setSizePolicy(sizePolicy)
        self.totalExportLabel_3.setMinimumSize(QtCore.QSize(60, 25))
        self.totalExportLabel_3.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.totalExportLabel_3.setFont(font)
        self.totalExportLabel_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportLabel_3.setStyleSheet(_fromUtf8("background-color:#FFFFFF;"))
        self.totalExportLabel_3.setFrameShape(QtGui.QFrame.Box)
        self.totalExportLabel_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.totalExportLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.totalExportLabel_3.setObjectName(_fromUtf8("totalExportLabel_3"))
        self.totalExportLayout.addWidget(self.totalExportLabel_3)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.totalExportLayout)
        self.bookLayout = QtGui.QHBoxLayout()
        self.bookLayout.setContentsMargins(0, -1, -1, -1)
        self.bookLayout.setSpacing(0)
        self.bookLayout.setObjectName(_fromUtf8("bookLayout"))
        self.bookLabel = QtGui.QLabel(self.centralwidget)
        self.bookLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.bookLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.bookLabel.setFont(font)
        self.bookLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bookLabel.setStyleSheet(_fromUtf8("padding-left:5px;background-color:#CCCCCC;color:#000000;"))
        self.bookLabel.setObjectName(_fromUtf8("bookLabel"))
        self.bookLayout.addWidget(self.bookLabel)
        spacerItem9 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.bookLayout.addItem(spacerItem9)
        self.bookSelector = QtGui.QComboBox(self.centralwidget)
        self.bookSelector.setEnabled(True)
        self.bookSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.bookSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.bookSelector.setFont(font)
        self.bookSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bookSelector.setAutoFillBackground(False)
        self.bookSelector.setStyleSheet(_fromUtf8("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
""))
        self.bookSelector.setEditable(False)
        self.bookSelector.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.bookSelector.setFrame(True)
        self.bookSelector.setModelColumn(0)
        self.bookSelector.setObjectName(_fromUtf8("bookSelector"))
        self.bookLayout.addWidget(self.bookSelector)
        self.verticalLayout_2.addLayout(self.bookLayout)
        self.startingChapterLayout = QtGui.QHBoxLayout()
        self.startingChapterLayout.setSpacing(0)
        self.startingChapterLayout.setObjectName(_fromUtf8("startingChapterLayout"))
        self.startingChapterLabel = QtGui.QLabel(self.centralwidget)
        self.startingChapterLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.startingChapterLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.startingChapterLabel.setFont(font)
        self.startingChapterLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.startingChapterLabel.setStyleSheet(_fromUtf8("padding-left:5px;background-color:#CCCCCC;color:#000000;"))
        self.startingChapterLabel.setObjectName(_fromUtf8("startingChapterLabel"))
        self.startingChapterLayout.addWidget(self.startingChapterLabel)
        spacerItem10 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.startingChapterLayout.addItem(spacerItem10)
        self.startingChapterSelector = QtGui.QComboBox(self.centralwidget)
        self.startingChapterSelector.setEnabled(True)
        self.startingChapterSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.startingChapterSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.startingChapterSelector.setFont(font)
        self.startingChapterSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.startingChapterSelector.setAutoFillBackground(False)
        self.startingChapterSelector.setStyleSheet(_fromUtf8("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
""))
        self.startingChapterSelector.setEditable(False)
        self.startingChapterSelector.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.startingChapterSelector.setFrame(True)
        self.startingChapterSelector.setModelColumn(0)
        self.startingChapterSelector.setObjectName(_fromUtf8("startingChapterSelector"))
        self.startingChapterLayout.addWidget(self.startingChapterSelector)
        self.verticalLayout_2.addLayout(self.startingChapterLayout)
        self.endingChapterLayout_5 = QtGui.QHBoxLayout()
        self.endingChapterLayout_5.setSpacing(0)
        self.endingChapterLayout_5.setObjectName(_fromUtf8("endingChapterLayout_5"))
        self.endingChapterLabel = QtGui.QLabel(self.centralwidget)
        self.endingChapterLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.endingChapterLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.endingChapterLabel.setFont(font)
        self.endingChapterLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.endingChapterLabel.setStyleSheet(_fromUtf8("padding-left:5px;background-color:#CCCCCC;color:#000000;"))
        self.endingChapterLabel.setObjectName(_fromUtf8("endingChapterLabel"))
        self.endingChapterLayout_5.addWidget(self.endingChapterLabel)
        spacerItem11 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.endingChapterLayout_5.addItem(spacerItem11)
        self.endingChapterSelector = QtGui.QComboBox(self.centralwidget)
        self.endingChapterSelector.setEnabled(True)
        self.endingChapterSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.endingChapterSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.endingChapterSelector.setFont(font)
        self.endingChapterSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.endingChapterSelector.setAutoFillBackground(False)
        self.endingChapterSelector.setStyleSheet(_fromUtf8("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
""))
        self.endingChapterSelector.setEditable(False)
        self.endingChapterSelector.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.endingChapterSelector.setFrame(True)
        self.endingChapterSelector.setModelColumn(0)
        self.endingChapterSelector.setObjectName(_fromUtf8("endingChapterSelector"))
        self.endingChapterLayout_5.addWidget(self.endingChapterSelector)
        self.verticalLayout_2.addLayout(self.endingChapterLayout_5)
        self.fontLayoutMain = QtGui.QHBoxLayout()
        self.fontLayoutMain.setSpacing(0)
        self.fontLayoutMain.setObjectName(_fromUtf8("fontLayoutMain"))
        self.fontLayoutSub_1 = QtGui.QVBoxLayout()
        self.fontLayoutSub_1.setObjectName(_fromUtf8("fontLayoutSub_1"))
        self.fontLabel = QtGui.QLabel(self.centralwidget)
        self.fontLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.fontLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fontLabel.setFont(font)
        self.fontLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabel.setStyleSheet(_fromUtf8("padding-left:5px;background-color:#CCCCCC;color:#000000;"))
        self.fontLabel.setObjectName(_fromUtf8("fontLabel"))
        self.fontLayoutSub_1.addWidget(self.fontLabel)
        spacerItem12 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.fontLayoutSub_1.addItem(spacerItem12)
        self.fontSelector = QtGui.QComboBox(self.centralwidget)
        self.fontSelector.setEnabled(True)
        self.fontSelector.setMinimumSize(QtCore.QSize(250, 25))
        self.fontSelector.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fontSelector.setFont(font)
        self.fontSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontSelector.setAutoFillBackground(False)
        self.fontSelector.setStyleSheet(_fromUtf8("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
""))
        self.fontSelector.setEditable(False)
        self.fontSelector.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.fontSelector.setFrame(True)
        self.fontSelector.setObjectName(_fromUtf8("fontSelector"))
        self.fontLayoutSub_1.addWidget(self.fontSelector)
        self.fontLayoutMain.addLayout(self.fontLayoutSub_1)
        spacerItem13 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.fontLayoutMain.addItem(spacerItem13)
        self.fontLayoutSub_2 = QtGui.QVBoxLayout()
        self.fontLayoutSub_2.setObjectName(_fromUtf8("fontLayoutSub_2"))
        self.fontLabelPreview_1 = QtGui.QLabel(self.centralwidget)
        self.fontLabelPreview_1.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_1.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fontLabelPreview_1.setFont(font)
        self.fontLabelPreview_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_1.setStyleSheet(_fromUtf8("background-color:#CCCCCC;color:#000000;"))
        self.fontLabelPreview_1.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_1.setObjectName(_fromUtf8("fontLabelPreview_1"))
        self.fontLayoutSub_2.addWidget(self.fontLabelPreview_1)
        spacerItem14 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.fontLayoutSub_2.addItem(spacerItem14)
        self.fontLabelPreview_2 = QtGui.QLabel(self.centralwidget)
        self.fontLabelPreview_2.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fontLabelPreview_2.setFont(font)
        self.fontLabelPreview_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_2.setStyleSheet(_fromUtf8("background-color:#CCCCCC;color:#000000;"))
        self.fontLabelPreview_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_2.setObjectName(_fromUtf8("fontLabelPreview_2"))
        self.fontLayoutSub_2.addWidget(self.fontLabelPreview_2)
        self.fontLayoutMain.addLayout(self.fontLayoutSub_2)
        spacerItem15 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.fontLayoutMain.addItem(spacerItem15)
        self.fontLayoutSub_3 = QtGui.QVBoxLayout()
        self.fontLayoutSub_3.setObjectName(_fromUtf8("fontLayoutSub_3"))
        self.fontLabelPreview_3 = QtGui.QLabel(self.centralwidget)
        self.fontLabelPreview_3.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fontLabelPreview_3.setFont(font)
        self.fontLabelPreview_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_3.setStyleSheet(_fromUtf8("background-color:#CCCCCC;color:#000000;"))
        self.fontLabelPreview_3.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_3.setObjectName(_fromUtf8("fontLabelPreview_3"))
        self.fontLayoutSub_3.addWidget(self.fontLabelPreview_3)
        spacerItem16 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.fontLayoutSub_3.addItem(spacerItem16)
        self.fontLabelPreview_4 = QtGui.QLabel(self.centralwidget)
        self.fontLabelPreview_4.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fontLabelPreview_4.setFont(font)
        self.fontLabelPreview_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_4.setStyleSheet(_fromUtf8("background-color:#CCCCCC;color:#000000;"))
        self.fontLabelPreview_4.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_4.setObjectName(_fromUtf8("fontLabelPreview_4"))
        self.fontLayoutSub_3.addWidget(self.fontLabelPreview_4)
        self.fontLayoutMain.addLayout(self.fontLayoutSub_3)
        self.verticalLayout_2.addLayout(self.fontLayoutMain)
        spacerItem17 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem17)
        self.statusProgressBar = QtGui.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.statusProgressBar.setFont(font)
        self.statusProgressBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.statusProgressBar.setProperty("value", 0)
        self.statusProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.statusProgressBar.setObjectName(_fromUtf8("statusProgressBar"))
        self.verticalLayout_2.addWidget(self.statusProgressBar)
        spacerItem18 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem18)
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.statusLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.statusLabel.setFont(font)
        self.statusLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.statusLabel.setStyleSheet(_fromUtf8("background-color:#CCCCCC;color:#000000;"))
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.verticalLayout_2.addWidget(self.statusLabel)
        spacerItem19 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem19)
        self.endButtonsLayout = QtGui.QHBoxLayout()
        self.endButtonsLayout.setSpacing(0)
        self.endButtonsLayout.setObjectName(_fromUtf8("endButtonsLayout"))
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setMinimumSize(QtCore.QSize(130, 30))
        self.exitButton.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.exitButton.setFont(font)
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.exitButton.setStyleSheet(_fromUtf8("background-color:#ff0000;color:#ffffff;"))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.endButtonsLayout.addWidget(self.exitButton)
        spacerItem20 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.endButtonsLayout.addItem(spacerItem20)
        self.previewButton = QtGui.QPushButton(self.centralwidget)
        self.previewButton.setMinimumSize(QtCore.QSize(0, 30))
        self.previewButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.previewButton.setFont(font)
        self.previewButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previewButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.previewButton.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);"))
        self.previewButton.setObjectName(_fromUtf8("previewButton"))
        self.endButtonsLayout.addWidget(self.previewButton)
        spacerItem21 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.endButtonsLayout.addItem(spacerItem21)
        self.generateButton = QtGui.QPushButton(self.centralwidget)
        self.generateButton.setMinimumSize(QtCore.QSize(0, 30))
        self.generateButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.generateButton.setFont(font)
        self.generateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generateButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.generateButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 212, 0);\n"
"color: rgb(255, 255, 255);"))
        self.generateButton.setObjectName(_fromUtf8("generateButton"))
        self.endButtonsLayout.addWidget(self.generateButton)
        self.verticalLayout_2.addLayout(self.endButtonsLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Wuxiaworld export ebook", None))
        self.novelLabel.setText(_translate("MainWindow", "Select Novel", None))
        self.modeLabel_1.setText(_translate("MainWindow", "Export mode", None))
        self.modeLabel_2.setText(_translate("MainWindow", "Classic", None))
        self.modeLabel_3.setText(_translate("MainWindow", "Alternative", None))
        self.totalExportLabel_1.setText(_translate("MainWindow", "Total export", None))
        self.totalExportLabel_2.setText(_translate("MainWindow", "Oui", None))
        self.totalExportLabel_3.setText(_translate("MainWindow", "Non", None))
        self.bookLabel.setText(_translate("MainWindow", "Select Book", None))
        self.startingChapterLabel.setText(_translate("MainWindow", "Starting Chapter", None))
        self.endingChapterLabel.setText(_translate("MainWindow", "Starting Chapter", None))
        self.fontLabel.setText(_translate("MainWindow", "Style Text Font", None))
        self.fontLabelPreview_1.setText(_translate("MainWindow", "Preview Regular", None))
        self.fontLabelPreview_2.setText(_translate("MainWindow", "Preview Italic", None))
        self.fontLabelPreview_3.setText(_translate("MainWindow", "Preview Bold", None))
        self.fontLabelPreview_4.setText(_translate("MainWindow", "Preview Bold-Italic", None))
        self.statusLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.exitButton.setText(_translate("MainWindow", "&Exit", None))
        self.previewButton.setText(_translate("MainWindow", "&Style Preview", None))
        self.generateButton.setText(_translate("MainWindow", "&Generate", None))

import r_rc
