# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 420))
        MainWindow.setMaximumSize(QtCore.QSize(650, 420))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet("background-color:#f8f8f8;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(650, 420))
        self.centralwidget.setMaximumSize(QtCore.QSize(650, 420))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.novelLayout = QtWidgets.QHBoxLayout()
        self.novelLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.novelLayout.setContentsMargins(0, 0, 0, 0)
        self.novelLayout.setSpacing(0)
        self.novelLayout.setObjectName("novelLayout")
        self.novelLabel = QtWidgets.QLabel(self.centralwidget)
        self.novelLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.novelLabel.sizePolicy().hasHeightForWidth())
        self.novelLabel.setSizePolicy(sizePolicy)
        self.novelLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.novelLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.novelLabel.setFont(font)
        self.novelLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.novelLabel.setStyleSheet("padding-left:5px;background-color:#CCCCCC;color:#000000;")
        self.novelLabel.setObjectName("novelLabel")
        self.novelLayout.addWidget(self.novelLabel)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.novelLayout.addItem(spacerItem)
        self.novelSelector = QtWidgets.QComboBox(self.centralwidget)
        self.novelSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.novelSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.novelSelector.setFont(font)
        self.novelSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.novelSelector.setStyleSheet("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
"")
        self.novelSelector.setFrame(True)
        self.novelSelector.setObjectName("novelSelector")
        self.novelLayout.addWidget(self.novelSelector)
        self.verticalLayout_2.addLayout(self.novelLayout)
        self.modeLayout = QtWidgets.QHBoxLayout()
        self.modeLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.modeLayout.setContentsMargins(0, -1, -1, -1)
        self.modeLayout.setSpacing(0)
        self.modeLayout.setObjectName("modeLayout")
        self.modeLabel_1 = QtWidgets.QLabel(self.centralwidget)
        self.modeLabel_1.setMinimumSize(QtCore.QSize(250, 25))
        self.modeLabel_1.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.modeLabel_1.setFont(font)
        self.modeLabel_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeLabel_1.setStyleSheet("padding-left:5px;background-color:#CCCCCC;color:#000000;")
        self.modeLabel_1.setObjectName("modeLabel_1")
        self.modeLayout.addWidget(self.modeLabel_1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem1)
        self.modeLabel_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeLabel_2.sizePolicy().hasHeightForWidth())
        self.modeLabel_2.setSizePolicy(sizePolicy)
        self.modeLabel_2.setMinimumSize(QtCore.QSize(60, 25))
        self.modeLabel_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.modeLabel_2.setFont(font)
        self.modeLabel_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeLabel_2.setStyleSheet("background-color:#FFFFFF;")
        self.modeLabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.modeLabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.modeLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.modeLabel_2.setObjectName("modeLabel_2")
        self.modeLayout.addWidget(self.modeLabel_2)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem2)
        self.modeSlider = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.modeSlider.setFont(font)
        self.modeSlider.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeSlider.setMinimum(0)
        self.modeSlider.setMaximum(1)
        self.modeSlider.setProperty("value", 0)
        self.modeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.modeSlider.setObjectName("modeSlider")
        self.modeLayout.addWidget(self.modeSlider)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem3)
        self.modeLabel_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeLabel_3.sizePolicy().hasHeightForWidth())
        self.modeLabel_3.setSizePolicy(sizePolicy)
        self.modeLabel_3.setMinimumSize(QtCore.QSize(60, 25))
        self.modeLabel_3.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.modeLabel_3.setFont(font)
        self.modeLabel_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.modeLabel_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.modeLabel_3.setStyleSheet("background-color:#FFFFFF;")
        self.modeLabel_3.setFrameShape(QtWidgets.QFrame.Box)
        self.modeLabel_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.modeLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.modeLabel_3.setObjectName("modeLabel_3")
        self.modeLayout.addWidget(self.modeLabel_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.modeLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.modeLayout)
        self.totalExportLayout = QtWidgets.QHBoxLayout()
        self.totalExportLayout.setContentsMargins(0, -1, -1, -1)
        self.totalExportLayout.setSpacing(0)
        self.totalExportLayout.setObjectName("totalExportLayout")
        self.totalExportLabel_1 = QtWidgets.QLabel(self.centralwidget)
        self.totalExportLabel_1.setMinimumSize(QtCore.QSize(250, 25))
        self.totalExportLabel_1.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.totalExportLabel_1.setFont(font)
        self.totalExportLabel_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportLabel_1.setStyleSheet("padding-left:5px;background-color:#CCCCCC;color:#000000;")
        self.totalExportLabel_1.setObjectName("totalExportLabel_1")
        self.totalExportLayout.addWidget(self.totalExportLabel_1)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem5)
        self.totalExportLabel_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalExportLabel_2.sizePolicy().hasHeightForWidth())
        self.totalExportLabel_2.setSizePolicy(sizePolicy)
        self.totalExportLabel_2.setMinimumSize(QtCore.QSize(60, 25))
        self.totalExportLabel_2.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.totalExportLabel_2.setFont(font)
        self.totalExportLabel_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportLabel_2.setStyleSheet("background-color:#FFFFFF;")
        self.totalExportLabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.totalExportLabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.totalExportLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.totalExportLabel_2.setObjectName("totalExportLabel_2")
        self.totalExportLayout.addWidget(self.totalExportLabel_2)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem6)
        self.totalExportSlider = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.totalExportSlider.setFont(font)
        self.totalExportSlider.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportSlider.setMaximum(1)
        self.totalExportSlider.setProperty("value", 0)
        self.totalExportSlider.setOrientation(QtCore.Qt.Horizontal)
        self.totalExportSlider.setInvertedAppearance(True)
        self.totalExportSlider.setObjectName("totalExportSlider")
        self.totalExportLayout.addWidget(self.totalExportSlider)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem7)
        self.totalExportLabel_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalExportLabel_3.sizePolicy().hasHeightForWidth())
        self.totalExportLabel_3.setSizePolicy(sizePolicy)
        self.totalExportLabel_3.setMinimumSize(QtCore.QSize(60, 25))
        self.totalExportLabel_3.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.totalExportLabel_3.setFont(font)
        self.totalExportLabel_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.totalExportLabel_3.setStyleSheet("background-color:#FFFFFF;")
        self.totalExportLabel_3.setFrameShape(QtWidgets.QFrame.Box)
        self.totalExportLabel_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.totalExportLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.totalExportLabel_3.setObjectName("totalExportLabel_3")
        self.totalExportLayout.addWidget(self.totalExportLabel_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.totalExportLayout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.totalExportLayout)
        self.bookLayout = QtWidgets.QHBoxLayout()
        self.bookLayout.setContentsMargins(0, -1, -1, -1)
        self.bookLayout.setSpacing(0)
        self.bookLayout.setObjectName("bookLayout")
        self.bookLabel = QtWidgets.QLabel(self.centralwidget)
        self.bookLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.bookLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bookLabel.setFont(font)
        self.bookLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bookLabel.setStyleSheet("padding-left:5px;background-color:#CCCCCC;color:#000000;")
        self.bookLabel.setObjectName("bookLabel")
        self.bookLayout.addWidget(self.bookLabel)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bookLayout.addItem(spacerItem9)
        self.bookSelector = QtWidgets.QComboBox(self.centralwidget)
        self.bookSelector.setEnabled(True)
        self.bookSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.bookSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.bookSelector.setFont(font)
        self.bookSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bookSelector.setAutoFillBackground(False)
        self.bookSelector.setStyleSheet("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
"")
        self.bookSelector.setEditable(False)
        self.bookSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.bookSelector.setFrame(True)
        self.bookSelector.setModelColumn(0)
        self.bookSelector.setObjectName("bookSelector")
        self.bookLayout.addWidget(self.bookSelector)
        self.verticalLayout_2.addLayout(self.bookLayout)
        self.startingChapterLayout = QtWidgets.QHBoxLayout()
        self.startingChapterLayout.setSpacing(0)
        self.startingChapterLayout.setObjectName("startingChapterLayout")
        self.startingChapterLabel = QtWidgets.QLabel(self.centralwidget)
        self.startingChapterLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.startingChapterLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.startingChapterLabel.setFont(font)
        self.startingChapterLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.startingChapterLabel.setStyleSheet("padding-left:5px;background-color:#CCCCCC;color:#000000;")
        self.startingChapterLabel.setObjectName("startingChapterLabel")
        self.startingChapterLayout.addWidget(self.startingChapterLabel)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.startingChapterLayout.addItem(spacerItem10)
        self.startingChapterSelector = QtWidgets.QComboBox(self.centralwidget)
        self.startingChapterSelector.setEnabled(True)
        self.startingChapterSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.startingChapterSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.startingChapterSelector.setFont(font)
        self.startingChapterSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.startingChapterSelector.setAutoFillBackground(False)
        self.startingChapterSelector.setStyleSheet("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
"")
        self.startingChapterSelector.setEditable(False)
        self.startingChapterSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.startingChapterSelector.setFrame(True)
        self.startingChapterSelector.setModelColumn(0)
        self.startingChapterSelector.setObjectName("startingChapterSelector")
        self.startingChapterLayout.addWidget(self.startingChapterSelector)
        self.verticalLayout_2.addLayout(self.startingChapterLayout)
        self.endingChapterLayout_5 = QtWidgets.QHBoxLayout()
        self.endingChapterLayout_5.setSpacing(0)
        self.endingChapterLayout_5.setObjectName("endingChapterLayout_5")
        self.endingChapterLabel = QtWidgets.QLabel(self.centralwidget)
        self.endingChapterLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.endingChapterLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.endingChapterLabel.setFont(font)
        self.endingChapterLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.endingChapterLabel.setStyleSheet("padding-left:5px;background-color:#CCCCCC;color:#000000;")
        self.endingChapterLabel.setObjectName("endingChapterLabel")
        self.endingChapterLayout_5.addWidget(self.endingChapterLabel)
        spacerItem11 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.endingChapterLayout_5.addItem(spacerItem11)
        self.endingChapterSelector = QtWidgets.QComboBox(self.centralwidget)
        self.endingChapterSelector.setEnabled(True)
        self.endingChapterSelector.setMinimumSize(QtCore.QSize(0, 25))
        self.endingChapterSelector.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.endingChapterSelector.setFont(font)
        self.endingChapterSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.endingChapterSelector.setAutoFillBackground(False)
        self.endingChapterSelector.setStyleSheet("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
"")
        self.endingChapterSelector.setEditable(False)
        self.endingChapterSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.endingChapterSelector.setFrame(True)
        self.endingChapterSelector.setModelColumn(0)
        self.endingChapterSelector.setObjectName("endingChapterSelector")
        self.endingChapterLayout_5.addWidget(self.endingChapterSelector)
        self.verticalLayout_2.addLayout(self.endingChapterLayout_5)
        self.fontLayoutMain = QtWidgets.QHBoxLayout()
        self.fontLayoutMain.setSpacing(0)
        self.fontLayoutMain.setObjectName("fontLayoutMain")
        self.fontLayoutSub_1 = QtWidgets.QVBoxLayout()
        self.fontLayoutSub_1.setObjectName("fontLayoutSub_1")
        self.fontLabel = QtWidgets.QLabel(self.centralwidget)
        self.fontLabel.setMinimumSize(QtCore.QSize(250, 25))
        self.fontLabel.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fontLabel.setFont(font)
        self.fontLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabel.setStyleSheet("padding-left:5px;background-color:#CCCCCC;color:#000000;")
        self.fontLabel.setObjectName("fontLabel")
        self.fontLayoutSub_1.addWidget(self.fontLabel)
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.fontLayoutSub_1.addItem(spacerItem12)
        self.fontSelector = QtWidgets.QComboBox(self.centralwidget)
        self.fontSelector.setEnabled(True)
        self.fontSelector.setMinimumSize(QtCore.QSize(250, 25))
        self.fontSelector.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fontSelector.setFont(font)
        self.fontSelector.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontSelector.setAutoFillBackground(False)
        self.fontSelector.setStyleSheet("background-color:#dddddd;\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
"")
        self.fontSelector.setEditable(False)
        self.fontSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.fontSelector.setFrame(True)
        self.fontSelector.setObjectName("fontSelector")
        self.fontLayoutSub_1.addWidget(self.fontSelector)
        self.fontLayoutMain.addLayout(self.fontLayoutSub_1)
        spacerItem13 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.fontLayoutMain.addItem(spacerItem13)
        self.fontLayoutSub_2 = QtWidgets.QVBoxLayout()
        self.fontLayoutSub_2.setObjectName("fontLayoutSub_2")
        self.fontLabelPreview_1 = QtWidgets.QLabel(self.centralwidget)
        self.fontLabelPreview_1.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_1.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fontLabelPreview_1.setFont(font)
        self.fontLabelPreview_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_1.setStyleSheet("background-color:#CCCCCC;color:#000000;")
        self.fontLabelPreview_1.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_1.setObjectName("fontLabelPreview_1")
        self.fontLayoutSub_2.addWidget(self.fontLabelPreview_1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.fontLayoutSub_2.addItem(spacerItem14)
        self.fontLabelPreview_2 = QtWidgets.QLabel(self.centralwidget)
        self.fontLabelPreview_2.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fontLabelPreview_2.setFont(font)
        self.fontLabelPreview_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_2.setStyleSheet("background-color:#CCCCCC;color:#000000;")
        self.fontLabelPreview_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_2.setObjectName("fontLabelPreview_2")
        self.fontLayoutSub_2.addWidget(self.fontLabelPreview_2)
        self.fontLayoutMain.addLayout(self.fontLayoutSub_2)
        spacerItem15 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.fontLayoutMain.addItem(spacerItem15)
        self.fontLayoutSub_3 = QtWidgets.QVBoxLayout()
        self.fontLayoutSub_3.setObjectName("fontLayoutSub_3")
        self.fontLabelPreview_3 = QtWidgets.QLabel(self.centralwidget)
        self.fontLabelPreview_3.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fontLabelPreview_3.setFont(font)
        self.fontLabelPreview_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_3.setStyleSheet("background-color:#CCCCCC;color:#000000;")
        self.fontLabelPreview_3.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_3.setObjectName("fontLabelPreview_3")
        self.fontLayoutSub_3.addWidget(self.fontLabelPreview_3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.fontLayoutSub_3.addItem(spacerItem16)
        self.fontLabelPreview_4 = QtWidgets.QLabel(self.centralwidget)
        self.fontLabelPreview_4.setMinimumSize(QtCore.QSize(0, 25))
        self.fontLabelPreview_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fontLabelPreview_4.setFont(font)
        self.fontLabelPreview_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fontLabelPreview_4.setStyleSheet("background-color:#CCCCCC;color:#000000;")
        self.fontLabelPreview_4.setAlignment(QtCore.Qt.AlignCenter)
        self.fontLabelPreview_4.setObjectName("fontLabelPreview_4")
        self.fontLayoutSub_3.addWidget(self.fontLabelPreview_4)
        self.fontLayoutMain.addLayout(self.fontLayoutSub_3)
        self.verticalLayout_2.addLayout(self.fontLayoutMain)
        spacerItem17 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem17)
        self.statusProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.statusProgressBar.setFont(font)
        self.statusProgressBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.statusProgressBar.setProperty("value", 0)
        self.statusProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.statusProgressBar.setObjectName("statusProgressBar")
        self.verticalLayout_2.addWidget(self.statusProgressBar)
        spacerItem18 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem18)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.statusLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.statusLabel.setFont(font)
        self.statusLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.statusLabel.setStyleSheet("background-color:#CCCCCC;color:#000000;")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_2.addWidget(self.statusLabel)
        spacerItem19 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem19)
        self.endButtonsLayout = QtWidgets.QHBoxLayout()
        self.endButtonsLayout.setSpacing(0)
        self.endButtonsLayout.setObjectName("endButtonsLayout")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setMinimumSize(QtCore.QSize(130, 30))
        self.exitButton.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.exitButton.setFont(font)
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.exitButton.setStyleSheet("background-color:#ff0000;color:#ffffff;")
        self.exitButton.setObjectName("exitButton")
        self.endButtonsLayout.addWidget(self.exitButton)
        spacerItem20 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.endButtonsLayout.addItem(spacerItem20)
        self.previewButton = QtWidgets.QPushButton(self.centralwidget)
        self.previewButton.setMinimumSize(QtCore.QSize(0, 30))
        self.previewButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.previewButton.setFont(font)
        self.previewButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previewButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.previewButton.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.previewButton.setObjectName("previewButton")
        self.endButtonsLayout.addWidget(self.previewButton)
        spacerItem21 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.endButtonsLayout.addItem(spacerItem21)
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setMinimumSize(QtCore.QSize(0, 30))
        self.generateButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.generateButton.setFont(font)
        self.generateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generateButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.generateButton.setStyleSheet("background-color: rgb(0, 212, 0);\n"
"color: rgb(255, 255, 255);")
        self.generateButton.setObjectName("generateButton")
        self.endButtonsLayout.addWidget(self.generateButton)
        self.verticalLayout_2.addLayout(self.endButtonsLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Wuxiaworld export ebook", None))
        self.novelLabel.setText(_translate("MainWindow", "Select Novel", None))
        self.modeLabel_1.setText(_translate("MainWindow", "Export mode", None))
        self.modeLabel_2.setText(_translate("MainWindow", "Classic", None))
        self.modeLabel_3.setText(_translate("MainWindow", "Alternative", None))
        self.totalExportLabel_1.setText(_translate("MainWindow", "Total export", None))
        self.totalExportLabel_2.setText(_translate("MainWindow", "Oui", None))
        self.totalExportLabel_3.setText(_translate("MainWindow", "Non", None))
        self.bookLabel.setText(_translate("MainWindow", "Select Book", None))
        self.startingChapterLabel.setText(_translate("MainWindow", "Starting Chapter", None))
        self.endingChapterLabel.setText(_translate("MainWindow", "Ending Chapter", None))
        self.fontLabel.setText(_translate("MainWindow", "Style Text Font", None))
        self.fontLabelPreview_1.setText(_translate("MainWindow", "Preview Regular", None))
        self.fontLabelPreview_2.setText(_translate("MainWindow", "Preview Italic", None))
        self.fontLabelPreview_3.setText(_translate("MainWindow", "Preview Bold", None))
        self.fontLabelPreview_4.setText(_translate("MainWindow", "Preview Bold-Italic", None))
        self.statusLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.exitButton.setText(_translate("MainWindow", "&Exit", None))
        self.previewButton.setText(_translate("MainWindow", "&Style Preview", None))
        self.generateButton.setText(_translate("MainWindow", "&Generate", None))

import r_rc

